name: 'Production deployment'

concurrency: 1

on:
  push:
    branches:
      - Master
    paths:
      - 'backhouse_analytics/**'
jobs:
  deploy:
    name: 'Deploy bundle'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        working-directory: backhouse_analytics
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
          
  
  
